// Types for term.mjs (the one file; see its header).
export type Mark = 'ok' | 'warn' | 'fail' | 'skip';
export type Palette = { on: boolean; bold: (s: string) => string; dim: (s: string) => string; green: (s: string) => string; yellow: (s: string) => string; red: (s: string) => string; cyan: (s: string) => string };
export type MarkExtra = { ms?: number; extra?: string | null };
export type Writable = { write(s: string): unknown; isTTY?: boolean };
export type Spinner = { update(text: string): void; stop(line?: string): string | undefined };
export type Term = {
  color: boolean; tty: boolean; palette: Palette;
  line(s?: string): string; step(n: number, of: number, title: string): string; head(text: string): string;
  call(method: string, url: string, body?: unknown): string; called(status: number | null | undefined, ms: number | undefined, error?: string | null): string;
  mark(mark: Mark, text: string, x?: MarkExtra): string; ok(text: string, x?: MarkExtra): string; warn(text: string, x?: MarkExtra): string;
  fail(text: string, x?: MarkExtra): string; skip(text: string, x?: MarkExtra): string;
  note(text: string): string; say(text: string): string; next(label: string): string; cmd(cmd: string): string; info(text: string): string;
  json<T>(v: T): T; spinner(text: string): Spinner;
};
export declare const GLYPH: Readonly<Record<Mark, string>>;
export declare const SPIN: readonly string[];
export declare const MARKS: readonly Mark[];
export declare function colorOn(stream: { isTTY?: boolean } | null | undefined, env: Record<string, string | undefined> | null | undefined): boolean;
export declare function palette(on: boolean): Palette;
export declare function stripAnsi(s: string): string;
export declare function elapsed(t0: number, now?: number): number;
export declare function fmtMs(ms: number | null | undefined): string;
export declare function fmtAge(ms: number): string;
export declare function stepLine(n: number, of: number, title: string, p?: Palette): string;
export declare function headLine(text: string, p?: Palette): string;
export declare function callLine(method: string, url: string, body?: unknown, p?: Palette): string;
export declare function calledLine(status: number | null | undefined, ms: number | undefined, error?: string | null, p?: Palette): string;
export declare function markLine(mark: Mark, text: string, o?: MarkExtra, p?: Palette): string;
export declare function noteLine(text: string, p?: Palette): string;
export declare function sayLine(text: string): string;
export declare function nextLine(label: string, p?: Palette): string;
export declare function cmdLine(cmd: string, p?: Palette): string;
export declare function createTerm(o?: { out?: Writable; env?: Record<string, string | undefined>; color?: boolean; quiet?: boolean }): Term;
export declare function step(n: number, of: number, title: string): string;
export declare function call(method: string, url: string, body?: unknown): string;
export declare function called(status: number | null | undefined, ms: number | undefined, error?: string | null): string;
export declare function ok(text: string, x?: MarkExtra): string;
export declare function warn(text: string, x?: MarkExtra): string;
export declare function fail(text: string, x?: MarkExtra): string;
export declare function skip(text: string, x?: MarkExtra): string;
export declare function note(text: string): string;
export declare function next(label: string): string;
export declare function spinner(text: string): Spinner;
